apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: demo
  namespace: demo
spec:
  releaseName: demo
  chart:
    git: git@github.com:ttarczynski/gitops-demo.git
    ref: master
    path: charts/demo
