apiVersion: v1
kind: Service
metadata: 
  name: demo
  namespace: demo
spec:
  ports:
    - name: http
      nodePort: 30080
      port: 80
      targetPort: 80
  selector:
    app/name: app
    app/instance: blue
  type: NodePort
